### ISSUE TITLE
rfkill.patch，how to use ?

### ISSUE THREAD

**Issue by youling257** [Manouchehri/vi8#10]
I do not proficient linux，Please tell me for each terminal command
how to patch kernel？

**Comment by Manouchehri** [comment]
Have you tried looking up "how to compile a kernel" on Google or any search engine?

Support is still experimental and likely to break. I would advise not trying to run Linux if you aren't able to troubleshoot/research yourself.

**Comment by youling257** [comment]
thanks

**Comment by sigboe** [comment]
@youling257 I suggest starting to learn Linux on a computer that has support for Linux first. Linux became my biggest love when I was between 14 and 19, so many cool things you can do with it. Check out http://reddit.com/r/unixporn just to see what you can do.

**Comment by youling257** [comment]
someone tell me compile Androidx86 kernel each terminal command，https://sourceforge.net/p/android-x86/kernel/ci/kernel-4.4/tree/
“git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9
export ARCH=x86
export SUBARCH=x86_64
export PATH=~/prebuilts/x86_64-linux-android-4.9/bin:$PATH
export CROSS_COMPILE=x86_64-linux-android-
make android-x86_64_defconfig
make
make targz-pkg -i
”
then I can do this

root@youling257-ONDA-Tablet:/home/youling257/desktop/i686-linux-android-4.7-master#
export ARCH=x86
root@youling257-ONDA-Tablet:/home/youling257/desktop/i686-linux-android-4.7-master#
export SUBARCH=x86
root@youling257-ONDA-Tablet:/home/youling257/desktop/i686-linux-android-4.7-master#
export PATH=~/desktop/i686-linux-android-4.7-master/bin:$PATH
root@youling257-ONDA-Tablet:/home/youling257/desktop/i686-linux-android-4.7-master#
export CROSS_COMPILE=i686-linux-android-
root@youling257-ONDA-Tablet:/home/youling257/desktop/i686-linux-android-4.7-master#

root@youling257-ONDA-Tablet:/home/youling257/desktop/android-x86-kernel-d492a48442a
e0e068d8749f7c2ab828806c6c298# make android-x86_defconfig
root@youling257-ONDA-Tablet:/home/youling257/desktop/android-x86-kernel-d492a48442a
e0e068d8749f7c2ab828806c6c298# make
root@youling257-ONDA-Tablet:/home/youling257/desktop/android-x86-kernel-d492a48442a
e0e068d8749f7c2ab828806c6c298# make targz-pkg -i

so I request use rfkill.patch each terminal command

**Comment by youling257** [comment]
what ? in order to use rfkill.patch ，need recompile kernel tree ?

**Comment by youling257** [comment]
about rfkill.patch，I see some place ，@@ -168,6 +168,7 @@ ，@@ -172,6 +172,7 @@，@@ -167,6 +167,7 @@，which right ?
https://sourceforge.net/p/android-x86/kernel/ci/bb80f724827e49d507ef37a3ca525f6406bafa1e/#diff-3
https://github.com/hadess/rtl8723bs/issues/34#issuecomment-145751005
https://github.com/lwfinger/rtl8723bs_bt/issues/1#issuecomment-148896005
