### ISSUE TITLE
Building a grub efi

### ISSUE THREAD

**Issue by z3t0** [Manouchehri/vi8#5]
Can you please share how you managed to get the 32bit grub efi file? Thansk

**Comment by Manouchehri** [comment]
`bootia32.efi` is already compiled into Debian `debian-testing-amd64-i386-netinst.iso` (and Jessie as well, confirmed by @onitake). You won't need to compile it or download it from me if you use that image.

If you want to try out another distribution, I've uploaded a [bootia32.efi](https://github.com/Manouchehri/vi8/raw/master/bootia32.efi) that should work. I used [instructions](https://github.com/lopaka/instructions/blob/master/ubuntu-14.10-install-asus-x205ta.md) from @lopaka (his X205A GRUB2 EFI binary is exactly the same).

**Comment by z3t0** [comment]
@Manouchehri Thanks!
